---
- name: Install elasticsearch
  yum:
    name: "{{ packages_elasticsearch_EL7 }}"
    state: installed

- name: configure elastic search cluster name
  lineinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    regexp: '^cluster.name:'
    line: 'cluster.name: {{ graylog3_cluster_name }}'

- name: configure elasticsearch hostname
  lineinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    regexp: 'network.host:'
    line: 'network.host: localhost'

- name: Enable and start elasticsearch
  service:
    name: elasticsearch
    state: started
    enabled: yes

# Addition ; config heap-size
- name: Configure elasticsearch heap-size
  lineinfile:
    path: /etc/sysconfig/elasticsearch
    line: ES_HEAP_SIZE={{ graylog3_jvm_elasticsearch_heap }}
    regexp: '^(.*)ES_HEAP_SIZE=(.*)$'
  register: heapsizeline

- name: Restart elasticsearch if necessary
  service:
    name: elasticsearch
    state: restarted
  when: heapsizeline.changed



...
