---
- name: Install elasticsearch
  yum:
    name: "{{ item }}"
    state: installed
  with_items: "{{ packages_elasticsearch_EL7 }}"

- name: configure elastic search cluster name
  lineinfile: 
    path: /etc/elasticsearch/elasticsearch.yml
    regexp: '^cluster.name:' 
    line: 'cluster.name: {{graylog3_cluster_name}}' 

- name: configure elasticsearch hostname
  lineinfile: 
    path: /etc/elasticsearch/elasticsearch.yml
    regexp: 'network.host:' 
    line: 'network.host: localhost' 

- name: Enable and start elasticsearch
  service:
    name: elasticsearch
    state: started
    enabled: yes
...
