---
# uniqconsulting.graylog3/tasks/main.yml
- import_tasks: include-vars.yml

# repo configuration
- import_tasks: repos.yml
  tags: [graylog3,repo]

# openjdk installation
- import_tasks: java.yml
  tags: [graylog3,java]

# mongodb installation
- import_tasks: mongodb.yml
  tags: [graylog3,mongodb]

# elastic search installation and configuration
- import_tasks: elasticsearch.yml
  tags: [graylog3,elasticsearch]

# install and configure nginx reverse proxy
- import_tasks: nginx.yml
  tags: [graylog3,nginx]


# Copy & Register uQcCheck
- name: Copy uQcCheck File
  local_action: 
    module: copy
    src: tests/uQcCheck_graylog.yml
    dest: "{{ playbook_dir }}/uQcCheck/uQcCheck_graylog.yml"
  ignore_errors: yes
  tags:
  - graylog3
  - installation

- name: Register uQcCheck File
  local_action: 
    module: lineinfile
    line: "- import_playbook: uQcCheck/uQcCheck_graylog.yml"
    path: "{{ playbook_dir }}/task_99_uQcCheck.yml"
  ignore_errors: yes
  tags:
  - graylog3
  - installation
  