---
- name: Install MongoDB
  yum:
    name: "{{ vars['packages_mongodb_' + ( ansible_distribution | lower ) + ( ansible_distribution_major_version | lower ) ] }}" 
    state: installed


- name: Enable and start mongod
  service:
    name: mongod
    state: started
    enabled: yes
...
